version: '3'

services:
    
    # Mongo DB
    db:
        image: mongo
        restart: always
        environment:
            # MONGO_INITDB_ROOT_USERNAME: root
            # MONGO_INITDB_ROOT_PASSWORD: example
            # db: booking

    # Python API
    api:
        image:
        restart: always
        
    # Django
    front:


    # PHP & Python
    generator:
        build:
            context: services/generator
        restart: always
