version: '3'

services:
    
    # Mongo DB
    db:
        image: mongo
        container_name: mongo_vdm
        restart: always
        ports: 
            - 27017:27017

    # Python API
    # api:
    #     build:
    #         context: .
    #     image: api_vdm_img
    #         # context: services/api
    #     container_name: api_vdm
    #     restart: always
    #     volumes: 
    #         - ./api:/home/api
    #         # - "./api:/home/api:delegated"
    #         # - "./api/vdm:/home/api/vdm:delegated"
    #     working_dir: /home/api
    #     ports: 
    #         - 5000:5000
    #     # command: ls -l
    #     # command: 
    #         # bash -c "echo \"Test...\n\" pip3 install && python3 vdm/main.py"
    #         # python /home/api/vdm/main.py
    #     # command: python3 --version
    #     entrypoint: python3 vdm/main.py
    #     # entrypoint: cat
        
    # Django
    # front:
    #     build:
    #         context:

    # PHP & Python
    # generator:
    #     build:
    #         context: services/generator
    #     image: generator_vdm_img
    #     container_name: generator_vdm
    #     restart: always
    #     volumes: 
    #         - ./script.php:/home/script.php
    #         - ./watcher.py:/home/watcher.py
    #     entrypoint: php script.php
